### ISSUE TITLE
Install, run errors

### ISSUE THREAD

**Issue by Sigfried** [UWMooneyLab/VEDx#4]
install failing:

    ➜ pip install -r requirements.txt

    Collecting certifi==2018.4.16
      Using cached certifi-2018.4.16-py2.py3-none-any.whl (150 kB)
    Collecting click==6.7
      Using cached click-6.7-py2.py3-none-any.whl (71 kB)
    Collecting Flask==1.0.2
      Using cached Flask-1.0.2-py2.py3-none-any.whl (91 kB)
    Collecting itsdangerous==0.24
      Using cached itsdangerous-0.24.tar.gz (46 kB)
      Preparing metadata (setup.py) ... done
    Collecting Jinja2==2.10.1
      Using cached Jinja2-2.10.1-py2.py3-none-any.whl (124 kB)
    Collecting MarkupSafe==1.0
      Using cached MarkupSafe-1.0.tar.gz (14 kB)
      Preparing metadata (setup.py) ... error
      error: subprocess-exited-with-error

      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [6 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/private/var/folders/32/nlb9gx4d40zd2x5jkpwct57c0000gn/T/pip-install-xnc44x73/markupsafe_ee171e7736444b358e6001aa6ed6ab8f/setup.py", line 6, in <module>
              from setuptools import setup, Extension, Feature
          ImportError: cannot import name 'Feature' from 'setuptools' (/opt/homebrew/lib/python3.10/site-packages/setuptools/__init__.py)
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

Was able to pip install all the individual packages listed in requirements.txt, but after that I still can't run application.py

    ➜ python application.py
    Traceback (most recent call last):
      File "/Users/sigfried/git-repos/VEDx/application.py", line 5, in <module>
        from GenerateJSON import generateJSON_counts, generateJSON_scores
      File "/Users/sigfried/git-repos/VEDx/GenerateJSON.py", line 5, in <module>
        from DxCodeHandler.ICD9 import ICD9
    ModuleNotFoundError: No module named 'DxCodeHandler.ICD9'

**Comment by joeflack4** [comment]
Having same issue. It fails when installing `MarkupSafe`. The result is that my virtualenv has nothing installed in it.

I could comment `MarkupSafe` out in `requirements.txt` and try installing everything else, but @Sigfried already tried that, and still no go.

**Comment by joeflack4** [comment]
Can probably be fixed by changing requirements to `MarkupSafe==2.1.1`

**Comment by joeflack4** [comment]
Addressed by: #7
